"use client";

import { Logo } from "@/components/shared/Logo";
import { AnimatedSticker } from "@/components/shared/AnimatedSticker";
import Link from "next/link";

const SUPPORTED_TOOLS = [
  {
    name: "Claude Code",
    key: "claude_code",
    color: "#D63384",
    path: "~/.claude/projects/*/conversation.jsonl",
  },
  {
    name: "Cursor",
    key: "cursor",
    color: "#0D6EFD",
    path: "CSV from cursor.com API",
  },
  {
    name: "Codex",
    key: "codex",
    color: "#198754",
    path: "~/.codex/sessions/*/conversation.jsonl",
  },
  {
    name: "Gemini",
    key: "gemini",
    color: "#20C997",
    path: "~/.gemini/tmp/*/chats/session-*.json",
  },
  {
    name: "OpenCode",
    key: "opencode",
    color: "#6F42C1",
    path: "~/.local/share/opencode/storage/message/**/*.json",
  },
  {
    name: "Amp",
    key: "amp",
    color: "#CC9A06",
    path: "~/.ampcode/sessions/**/*.json",
  },
  {
    name: "Droid",
    key: "droid",
    color: "#DC3545",
    path: "~/Library/.../googleAiStudio/history/*.json",
  },
];

const TOKEN_TYPES = [
  {
    name: "Input Tokens",
    description: "Tokens sent to the model (your prompts, context, files)",
    color: "#0D6EFD",
  },
  {
    name: "Output Tokens",
    description: "Tokens generated by the model (responses, code)",
    color: "#198754",
  },
  {
    name: "Cache Read",
    description: "Cached prompt tokens reused from previous requests",
    color: "#6F42C1",
  },
  {
    name: "Cache Write",
    description: "Prompt tokens cached for future requests",
    color: "#CC9A06",
  },
  {
    name: "Reasoning",
    description: "Thinking/chain-of-thought tokens (extended thinking models)",
    color: "#D63384",
  },
];

export function MethodologyPage() {
  return (
    <div className="min-h-screen py-8 px-4">
      <div className="max-w-4xl mx-auto relative">
        {/* Stickers */}
        <div
          className="pointer-events-none select-none absolute inset-0 z-0 overflow-visible"
          aria-hidden="true"
        >
          {/* Top section */}
          <AnimatedSticker
            src="/stickers/vibe.webp"
            width={180}
            height={180}
            className="absolute top-[60px] -left-24 md:-left-44 lg:-left-52 w-32 md:w-44 rotate-[-12deg] hidden sm:block drop-shadow-lg"
            delay={100}
          />
          <AnimatedSticker
            src="/stickers/rainbow.webp"
            width={180}
            height={180}
            className="absolute top-[50px] -right-24 md:-right-44 lg:-right-52 w-32 md:w-44 rotate-[15deg] hidden sm:block drop-shadow-lg"
            delay={200}
          />
          {/* Tools section */}
          <AnimatedSticker
            src="/stickers/cursor_logo.webp"
            width={120}
            height={120}
            className="absolute top-[350px] -left-20 md:-left-36 lg:-left-44 w-24 md:w-32 rotate-[8deg] hidden md:block drop-shadow-lg"
            delay={300}
          />
          <AnimatedSticker
            src="/stickers/claude_logo.webp"
            width={140}
            height={140}
            className="absolute top-[380px] -right-24 md:-right-40 lg:-right-48 w-28 md:w-36 rotate-[-8deg] hidden md:block drop-shadow-lg"
            delay={400}
          />
          {/* Token types section */}
          <AnimatedSticker
            src="/stickers/cloud.webp"
            width={140}
            height={140}
            className="absolute top-[650px] -left-24 md:-left-40 lg:-left-48 w-28 md:w-36 rotate-[10deg] hidden md:block drop-shadow-lg"
            delay={500}
          />
          <AnimatedSticker
            src="/stickers/gpt_logo.webp"
            width={150}
            height={150}
            className="absolute top-[700px] -right-24 md:-right-44 lg:-right-52 w-30 md:w-40 rotate-[-10deg] hidden md:block drop-shadow-lg"
            delay={600}
          />
          {/* Parsing section */}
          <AnimatedSticker
            src="/stickers/banana.webp"
            width={100}
            height={100}
            className="absolute top-[950px] -right-20 md:-right-32 lg:-right-40 w-20 md:w-28 rotate-[12deg] hidden lg:block drop-shadow-lg"
            delay={700}
          />
          <AnimatedSticker
            src="/stickers/jensen.webp"
            width={150}
            height={150}
            className="absolute top-[1000px] -left-24 md:-left-40 lg:-left-48 w-30 md:w-40 rotate-[-6deg] hidden lg:block drop-shadow-lg"
            delay={800}
          />
          {/* Pricing section */}
          <AnimatedSticker
            src="/stickers/elon.webp"
            width={140}
            height={140}
            className="absolute top-[1300px] -right-24 md:-right-40 lg:-right-48 w-28 md:w-36 rotate-[8deg] hidden lg:block drop-shadow-lg"
            delay={900}
          />
          <AnimatedSticker
            src="/stickers/marck.webp"
            width={120}
            height={120}
            className="absolute top-[1350px] -left-20 md:-left-36 lg:-left-44 w-24 md:w-32 rotate-[-10deg] hidden lg:block drop-shadow-lg"
            delay={1000}
          />
          {/* Pipeline section */}
          <AnimatedSticker
            src="/stickers/no_em_dashes.webp"
            width={140}
            height={140}
            className="absolute top-[1650px] -left-24 md:-left-40 lg:-left-48 w-28 md:w-36 rotate-[12deg] hidden lg:block drop-shadow-lg"
            delay={1100}
          />
          <AnimatedSticker
            src="/stickers/cloud.webp"
            width={100}
            height={100}
            className="absolute top-[1700px] -right-20 md:-right-32 lg:-right-40 w-20 md:w-28 rotate-[-8deg] hidden lg:block drop-shadow-lg"
            delay={1200}
          />
          {/* Privacy section */}
          <AnimatedSticker
            src="/stickers/rainbow.webp"
            width={130}
            height={130}
            className="absolute top-[1950px] -right-24 md:-right-40 lg:-right-48 w-26 md:w-34 rotate-[10deg] hidden lg:block drop-shadow-lg"
            delay={1300}
          />
          <AnimatedSticker
            src="/stickers/vibe.webp"
            width={120}
            height={120}
            className="absolute top-[2000px] -left-24 md:-left-40 lg:-left-48 w-24 md:w-32 rotate-[-15deg] hidden lg:block drop-shadow-lg"
            delay={1400}
          />
        </div>

        <div className="relative z-10">
          {/* Header */}
          <header className="flex items-center justify-between mb-8">
            <Link href="/">
              <Logo />
            </Link>
          </header>

          {/* Title */}
          <div className="card mb-8">
            <h1 className="text-3xl font-bold mb-2">How We Count</h1>
            <p className="text-[#232323]/60">
              Our methodology for tracking AI coding tool usage
            </p>
          </div>

          {/* Section 1: Supported Tools */}
          <div className="card mb-6">
            <div className="flex items-center gap-3 mb-4">
              <span className="tag tag-pink">7 Tools</span>
              <h2 className="text-xl font-bold">Supported Tools</h2>
            </div>
            <p className="text-[#232323]/70 mb-4">
              We scan local session files from these AI coding assistants:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {SUPPORTED_TOOLS.map((tool) => (
                <div
                  key={tool.key}
                  className="flex items-start gap-3 p-3 bg-[#eef0f2] rounded-lg"
                >
                  <div
                    className="w-3 h-3 rounded-full mt-1.5 flex-shrink-0"
                    style={{ backgroundColor: tool.color }}
                  />
                  <div className="min-w-0">
                    <div className="font-semibold">{tool.name}</div>
                    <div className="text-xs text-[#232323]/50 font-mono truncate">
                      {tool.path}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 2: Token Types */}
          <div className="card mb-6">
            <div className="flex items-center gap-3 mb-4">
              <span className="tag tag-blue">5 Types</span>
              <h2 className="text-xl font-bold">Token Types</h2>
            </div>
            <p className="text-[#232323]/70 mb-4">
              We track 5 distinct token types for accurate cost calculation:
            </p>
            <div className="space-y-3">
              {TOKEN_TYPES.map((token) => (
                <div
                  key={token.name}
                  className="flex items-start gap-3 p-3 bg-[#eef0f2] rounded-lg"
                >
                  <div
                    className="w-3 h-3 rounded-full mt-1.5 flex-shrink-0"
                    style={{ backgroundColor: token.color }}
                  />
                  <div>
                    <div className="font-semibold">{token.name}</div>
                    <div className="text-sm text-[#232323]/60">
                      {token.description}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 3: Data Parsing */}
          <div className="card mb-6">
            <div className="flex items-center gap-3 mb-4">
              <span className="tag tag-green">Parsing</span>
              <h2 className="text-xl font-bold">How We Parse Data</h2>
            </div>
            <div className="space-y-4 text-[#232323]/80">
              <div>
                <h3 className="font-semibold mb-1">Claude Code</h3>
                <p className="text-sm">
                  JSONL format with global deduplication via{" "}
                  <code className="bg-[#eef0f2] px-1 rounded">
                    messageId:requestId
                  </code>{" "}
                  composite keys to prevent double-counting across session
                  files.
                </p>
              </div>
              <div>
                <h3 className="font-semibold mb-1">Codex</h3>
                <p className="text-sm">
                  JSONL with delta calculation from{" "}
                  <code className="bg-[#eef0f2] px-1 rounded">
                    total_token_usage
                  </code>
                  . We track state and compute token diffs between events.
                </p>
              </div>
              <div>
                <h3 className="font-semibold mb-1">Cursor</h3>
                <p className="text-sm">
                  CSV downloaded from cursor.com API. Cache write tokens
                  calculated as difference between{" "}
                  <code className="bg-[#eef0f2] px-1 rounded">
                    input_with_cache
                  </code>{" "}
                  and{" "}
                  <code className="bg-[#eef0f2] px-1 rounded">
                    input_without_cache
                  </code>
                  .
                </p>
              </div>
              <div>
                <h3 className="font-semibold mb-1">Gemini</h3>
                <p className="text-sm">
                  JSON format.{" "}
                  <code className="bg-[#eef0f2] px-1 rounded">
                    tokens.thoughts
                  </code>{" "}
                  mapped to reasoning tokens. Reasoning tokens count as output
                  for cost calculation.
                </p>
              </div>
              <div>
                <h3 className="font-semibold mb-1">OpenCode, Amp, Droid</h3>
                <p className="text-sm">
                  Standard JSON parsing with direct token breakdown extraction.
                </p>
              </div>
            </div>
          </div>

          {/* Section 4: Pricing Calculation */}
          <div className="card mb-6">
            <div className="flex items-center gap-3 mb-4">
              <span className="tag tag-yellow">Pricing</span>
              <h2 className="text-xl font-bold">Cost Calculation</h2>
            </div>
            <div className="space-y-4 text-[#232323]/80">
              <div>
                <h3 className="font-semibold mb-2">Two Pricing Sources</h3>
                <ul className="list-disc list-inside text-sm space-y-1">
                  <li>
                    <strong>LiteLLM</strong> - Primary source for most models
                  </li>
                  <li>
                    <strong>OpenRouter</strong> - Fallback for specialized models
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold mb-2">Formula</h3>
                <div className="bg-[#eef0f2] p-3 rounded-lg font-mono text-sm overflow-x-auto">
                  cost = (input × input_rate) + ((output + reasoning) ×
                  output_rate) + (cache_read × cache_read_rate) + (cache_write ×
                  cache_write_rate)
                </div>
              </div>
              <div>
                <h3 className="font-semibold mb-2">Intelligent Model Matching</h3>
                <p className="text-sm">
                  Multi-stage lookup: exact match → version normalization →
                  provider prefixes → suffix stripping → fuzzy family matching.
                  Prefers direct providers (anthropic/, openai/) over resellers
                  (azure/, bedrock/).
                </p>
              </div>
              <div className="text-sm text-[#232323]/60">
                Pricing data cached for 24 hours to minimize API calls.
              </div>
            </div>
          </div>

          {/* Section 5: Aggregation Pipeline */}
          <div className="card mb-6">
            <div className="flex items-center gap-3 mb-4">
              <span className="tag tag-pink">Pipeline</span>
              <h2 className="text-xl font-bold">Aggregation Pipeline</h2>
            </div>
            <div className="space-y-4">
              <div className="flex gap-4 items-start">
                <div className="w-8 h-8 rounded-full bg-[#D63384] text-white flex items-center justify-center font-bold flex-shrink-0">
                  1
                </div>
                <div>
                  <h3 className="font-semibold">Parallel Parsing</h3>
                  <p className="text-sm text-[#232323]/70">
                    Rust + rayon for parallel file scanning. simd-json for SIMD-accelerated JSON parsing.
                  </p>
                </div>
              </div>
              <div className="flex gap-4 items-start">
                <div className="w-8 h-8 rounded-full bg-[#0D6EFD] text-white flex items-center justify-center font-bold flex-shrink-0">
                  2
                </div>
                <div>
                  <h3 className="font-semibold">Price Lookup</h3>
                  <p className="text-sm text-[#232323]/70">
                    Fetch pricing from LiteLLM/OpenRouter. Apply intelligent
                    model matching. Calculate cost per message.
                  </p>
                </div>
              </div>
              <div className="flex gap-4 items-start">
                <div className="w-8 h-8 rounded-full bg-[#198754] text-white flex items-center justify-center font-bold flex-shrink-0">
                  3
                </div>
                <div>
                  <h3 className="font-semibold">Date Aggregation</h3>
                  <p className="text-sm text-[#232323]/70">
                    Parallel fold/reduce into daily buckets. Calculate intensity
                    (0-4) based on cost ratio to max day.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Section 6: Privacy */}
          <div className="card mb-8">
            <div className="flex items-center gap-3 mb-4">
              <span className="tag tag-green">Privacy</span>
              <h2 className="text-xl font-bold">Your Data, Your Control</h2>
            </div>
            <div className="space-y-3 text-[#232323]/80">
              <div className="flex items-start gap-3">
                <span className="text-xl">🔒</span>
                <p className="text-sm">
                  <strong>Local scanning only</strong> - All parsing happens on
                  your machine via our native CLI.
                </p>
              </div>
              <div className="flex items-start gap-3">
                <span className="text-xl">📤</span>
                <p className="text-sm">
                  <strong>Explicit submission</strong> - Data only leaves your
                  device when you click submit in the browser.
                </p>
              </div>
              <div className="flex items-start gap-3">
                <span className="text-xl">🚫</span>
                <p className="text-sm">
                  <strong>No telemetry</strong> - We don&apos;t track your usage
                  or send analytics. The CLI is fully open source.
                </p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <footer className="text-center text-sm text-[#232323]/50">
            <p>
              <Link href="/" className="underline hover:text-[#232323]/70">
                Back to Leaderboard
              </Link>
            </p>
          </footer>
        </div>
      </div>
    </div>
  );
}
